package utils;

import java.util.HashMap;
import java.util.Map;

public class Zone {
    public static final Map<Integer, String> staticMap = new HashMap<>();

    static {
        staticMap.put(1,"EWR,Newark Airport,EWR");
        staticMap.put(2,"Queens,Jamaica Bay,Boro Zone");
        staticMap.put(3,"Bronx,Allerton/Pelham Gardens,Boro Zone");
        staticMap.put(4,"Manhattan,Alphabet City,Yellow Zone");
        staticMap.put(5,"Staten Island,Arden Heights,Boro Zone");
        staticMap.put(6,"Staten Island,Arrochar/Fort Wadsworth,Boro Zone");
        staticMap.put(7,"Queens,Astoria,Boro Zone");
        staticMap.put(8,"Queens,Astoria Park,Boro Zone");
        staticMap.put(9,"Queens,Auburndale,Boro Zone");
        staticMap.put(10,"Queens,Baisley Park,Boro Zone");
        staticMap.put(11,"Brooklyn,Bath Beach,Boro Zone");
        staticMap.put(12,"Manhattan,Battery Park,Yellow Zone");
        staticMap.put(13,"Manhattan,Battery Park City,Yellow Zone");
        staticMap.put(14,"Brooklyn,Bay Ridge,Boro Zone");
        staticMap.put(15,"Queens,Bay Terrace/Fort Totten,Boro Zone");
        staticMap.put(16,"Queens,Bayside,Boro Zone");
        staticMap.put(17,"Brooklyn,Bedford,Boro Zone");
        staticMap.put(18,"Bronx,Bedford Park,Boro Zone");
        staticMap.put(19,"Queens,Bellerose,Boro Zone");
        staticMap.put(20,"Bronx,Belmont,Boro Zone");
        staticMap.put(21,"Brooklyn,Bensonhurst East,Boro Zone");
        staticMap.put(22,"Brooklyn,Bensonhurst West,Boro Zone");
        staticMap.put(23,"Staten Island,Bloomfield/Emerson Hill,Boro Zone");
        staticMap.put(24,"Manhattan,Bloomingdale,Yellow Zone");
        staticMap.put(25,"Brooklyn,Boerum Hill,Boro Zone");
        staticMap.put(26,"Brooklyn,Borough Park,Boro Zone");
        staticMap.put(27,"Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone");
        staticMap.put(28,"Queens,Briarwood/Jamaica Hills,Boro Zone");
        staticMap.put(29,"Brooklyn,Brighton Beach,Boro Zone");
        staticMap.put(30,"Queens,Broad Channel,Boro Zone");
        staticMap.put(31,"Bronx,Bronx Park,Boro Zone");
        staticMap.put(32,"Bronx,Bronxdale,Boro Zone");
        staticMap.put(33,"Brooklyn,Brooklyn Heights,Boro Zone");
        staticMap.put(34,"Brooklyn,Brooklyn Navy Yard,Boro Zone");
        staticMap.put(35,"Brooklyn,Brownsville,Boro Zone");
        staticMap.put(36,"Brooklyn,Bushwick North,Boro Zone");
        staticMap.put(37,"Brooklyn,Bushwick South,Boro Zone");
        staticMap.put(38,"Queens,Cambria Heights,Boro Zone");
        staticMap.put(39,"Brooklyn,Canarsie,Boro Zone");
        staticMap.put(40,"Brooklyn,Carroll Gardens,Boro Zone");
        staticMap.put(41,"Manhattan,Central Harlem,Boro Zone");
        staticMap.put(42,"Manhattan,Central Harlem North,Boro Zone");
        staticMap.put(43,"Manhattan,Central Park,Yellow Zone");
        staticMap.put(44,"Staten Island,Charleston/Tottenville,Boro Zone");
        staticMap.put(45,"Manhattan,Chinatown,Yellow Zone");
        staticMap.put(46,"Bronx,City Island,Boro Zone");
        staticMap.put(47,"Bronx,Claremont/Bathgate,Boro Zone");
        staticMap.put(48,"Manhattan,Clinton East,Yellow Zone");
        staticMap.put(49,"Brooklyn,Clinton Hill,Boro Zone");
        staticMap.put(50,"Manhattan,Clinton West,Yellow Zone");
        staticMap.put(51,"Bronx,Co-Op City,Boro Zone");
        staticMap.put(52,"Brooklyn,Cobble Hill,Boro Zone");
        staticMap.put(53,"Queens,College Point,Boro Zone");
        staticMap.put(54,"Brooklyn,Columbia Street,Boro Zone");
        staticMap.put(55,"Brooklyn,Coney Island,Boro Zone");
        staticMap.put(56,"Queens,Corona,Boro Zone");
        staticMap.put(57,"Queens,Corona,Boro Zone");
        staticMap.put(58,"Bronx,Country Club,Boro Zone");
        staticMap.put(59,"Bronx,Crotona Park,Boro Zone");
        staticMap.put(60,"Bronx,Crotona Park East,Boro Zone");
        staticMap.put(61,"Brooklyn,Crown Heights North,Boro Zone");
        staticMap.put(62,"Brooklyn,Crown Heights South,Boro Zone");
        staticMap.put(63,"Brooklyn,Cypress Hills,Boro Zone");
        staticMap.put(64,"Queens,Douglaston,Boro Zone");
        staticMap.put(65,"Brooklyn,Downtown Brooklyn/MetroTech,Boro Zone");
        staticMap.put(66,"Brooklyn,DUMBO/Vinegar Hill,Boro Zone");
        staticMap.put(67,"Brooklyn,Dyker Heights,Boro Zone");
        staticMap.put(68,"Manhattan,East Chelsea,Yellow Zone");
        staticMap.put(69,"Bronx,East Concourse/Concourse Village,Boro Zone");
        staticMap.put(70,"Queens,East Elmhurst,Boro Zone");
        staticMap.put(71,"Brooklyn,East Flatbush/Farragut,Boro Zone");
        staticMap.put(72,"Brooklyn,East Flatbush/Remsen Village,Boro Zone");
        staticMap.put(73,"Queens,East Flushing,Boro Zone");
        staticMap.put(74,"Manhattan,East Harlem North,Boro Zone");
        staticMap.put(75,"Manhattan,East Harlem South,Boro Zone");
        staticMap.put(76,"Brooklyn,East New York,Boro Zone");
        staticMap.put(77,"Brooklyn,East New York/Pennsylvania Avenue,Boro Zone");
        staticMap.put(78,"Bronx,East Tremont,Boro Zone");
        staticMap.put(79,"Manhattan,East Village,Yellow Zone");
        staticMap.put(80,"Brooklyn,East Williamsburg,Boro Zone");
        staticMap.put(81,"Bronx,Eastchester,Boro Zone");
        staticMap.put(82,"Queens,Elmhurst,Boro Zone");
        staticMap.put(83,"Queens,Elmhurst/Maspeth,Boro Zone");
        staticMap.put(84,"Staten Island,Eltingville/Annadale/Prince's Bay,Boro Zone");
        staticMap.put(85,"Brooklyn,Erasmus,Boro Zone");
        staticMap.put(86,"Queens,Far Rockaway,Boro Zone");
        staticMap.put(87,"Manhattan,Financial District North,Yellow Zone");
        staticMap.put(88,"Manhattan,Financial District South,Yellow Zone");
        staticMap.put(89,"Brooklyn,Flatbush/Ditmas Park,Boro Zone");
        staticMap.put(90,"Manhattan,Flatiron,Yellow Zone");
        staticMap.put(91,"Brooklyn,Flatlands,Boro Zone");
        staticMap.put(92,"Queens,Flushing,Boro Zone");
        staticMap.put(93,"Queens,Flushing Meadows-Corona Park,Boro Zone");
        staticMap.put(94,"Bronx,Fordham South,Boro Zone");
        staticMap.put(95,"Queens,Forest Hills,Boro Zone");
        staticMap.put(96,"Queens,Forest Park/Highland Park,Boro Zone");
        staticMap.put(97,"Brooklyn,Fort Greene,Boro Zone");
        staticMap.put(98,"Queens,Fresh Meadows,Boro Zone");
        staticMap.put(99,"Staten Island,Freshkills Park,Boro Zone");
        staticMap.put(100,"Manhattan,Garment District,Yellow Zone");
        staticMap.put(101,"Queens,Glen Oaks,Boro Zone");
        staticMap.put(102,"Queens,Glendale,Boro Zone");
        staticMap.put(103,"Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone");
        staticMap.put(104,"Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone");
        staticMap.put(105,"Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone");
        staticMap.put(106,"Brooklyn,Gowanus,Boro Zone");
        staticMap.put(107,"Manhattan,Gramercy,Yellow Zone");
        staticMap.put(108,"Brooklyn,Gravesend,Boro Zone");
        staticMap.put(109,"Staten Island,Great Kills,Boro Zone");
        staticMap.put(110,"Staten Island,Great Kills Park,Boro Zone");
        staticMap.put(111,"Brooklyn,Green-Wood Cemetery,Boro Zone");
        staticMap.put(112,"Brooklyn,Greenpoint,Boro Zone");
        staticMap.put(113,"Manhattan,Greenwich Village North,Yellow Zone");
        staticMap.put(114,"Manhattan,Greenwich Village South,Yellow Zone");
        staticMap.put(115,"Staten Island,Grymes Hill/Clifton,Boro Zone");
        staticMap.put(116,"Manhattan,Hamilton Heights,Boro Zone");
        staticMap.put(117,"Queens,Hammels/Arverne,Boro Zone");
        staticMap.put(118,"Staten Island,Heartland Village/Todt Hill,Boro Zone");
        staticMap.put(119,"Bronx,Highbridge,Boro Zone");
        staticMap.put(120,"Manhattan,Highbridge Park,Boro Zone");
        staticMap.put(121,"Queens,Hillcrest/Pomonok,Boro Zone");
        staticMap.put(122,"Queens,Hollis,Boro Zone");
        staticMap.put(123,"Brooklyn,Homecrest,Boro Zone");
        staticMap.put(124,"Queens,Howard Beach,Boro Zone");
        staticMap.put(125,"Manhattan,Hudson Sq,Yellow Zone");
        staticMap.put(126,"Bronx,Hunts Point,Boro Zone");
        staticMap.put(127,"Manhattan,Inwood,Boro Zone");
        staticMap.put(128,"Manhattan,Inwood Hill Park,Boro Zone");
        staticMap.put(129,"Queens,Jackson Heights,Boro Zone");
        staticMap.put(130,"Queens,Jamaica,Boro Zone");
        staticMap.put(131,"Queens,Jamaica Estates,Boro Zone");
        staticMap.put(132,"Queens,JFK Airport,Airports");
        staticMap.put(133,"Brooklyn,Kensington,Boro Zone");
        staticMap.put(134,"Queens,Kew Gardens,Boro Zone");
        staticMap.put(135,"Queens,Kew Gardens Hills,Boro Zone");
        staticMap.put(136,"Bronx,Kingsbridge Heights,Boro Zone");
        staticMap.put(137,"Manhattan,Kips Bay,Yellow Zone");
        staticMap.put(138,"Queens,LaGuardia Airport,Airports");
        staticMap.put(139,"Queens,Laurelton,Boro Zone");
        staticMap.put(140,"Manhattan,Lenox Hill East,Yellow Zone");
        staticMap.put(141,"Manhattan,Lenox Hill West,Yellow Zone");
        staticMap.put(142,"Manhattan,Lincoln Square East,Yellow Zone");
        staticMap.put(143,"Manhattan,Lincoln Square West,Yellow Zone");
        staticMap.put(144,"Manhattan,Little Italy/NoLiTa,Yellow Zone");
        staticMap.put(145,"Queens,Long Island City/Hunters Point,Boro Zone");
        staticMap.put(146,"Queens,Long Island City/Queens Plaza,Boro Zone");
        staticMap.put(147,"Bronx,Longwood,Boro Zone");
        staticMap.put(148,"Manhattan,Lower East Side,Yellow Zone");
        staticMap.put(149,"Brooklyn,Madison,Boro Zone");
        staticMap.put(150,"Brooklyn,Manhattan Beach,Boro Zone");
        staticMap.put(151,"Manhattan,Manhattan Valley,Yellow Zone");
        staticMap.put(152,"Manhattan,Manhattanville,Boro Zone");
        staticMap.put(153,"Manhattan,Marble Hill,Boro Zone");
        staticMap.put(154,"Brooklyn,Marine Park/Floyd Bennett Field,Boro Zone");
        staticMap.put(155,"Brooklyn,Marine Park/Mill Basin,Boro Zone");
        staticMap.put(156,"Staten Island,Mariners Harbor,Boro Zone");
        staticMap.put(157,"Queens,Maspeth,Boro Zone");
        staticMap.put(158,"Manhattan,Meatpacking/West Village West,Yellow Zone");
        staticMap.put(159,"Bronx,Melrose South,Boro Zone");
        staticMap.put(160,"Queens,Middle Village,Boro Zone");
        staticMap.put(161,"Manhattan,Midtown Center,Yellow Zone");
        staticMap.put(162,"Manhattan,Midtown East,Yellow Zone");
        staticMap.put(163,"Manhattan,Midtown North,Yellow Zone");
        staticMap.put(164,"Manhattan,Midtown South,Yellow Zone");
        staticMap.put(165,"Brooklyn,Midwood,Boro Zone");
        staticMap.put(166,"Manhattan,Morningside Heights,Boro Zone");
        staticMap.put(167,"Bronx,Morrisania/Melrose,Boro Zone");
        staticMap.put(168,"Bronx,Mott Haven/Port Morris,Boro Zone");
        staticMap.put(169,"Bronx,Mount Hope,Boro Zone");
        staticMap.put(170,"Manhattan,Murray Hill,Yellow Zone");
        staticMap.put(171,"Queens,Murray Hill-Queens,Boro Zone");
        staticMap.put(172,"Staten Island,New Dorp/Midland Beach,Boro Zone");
        staticMap.put(173,"Queens,North Corona,Boro Zone");
        staticMap.put(174,"Bronx,Norwood,Boro Zone");
        staticMap.put(175,"Queens,Oakland Gardens,Boro Zone");
        staticMap.put(176,"Staten Island,Oakwood,Boro Zone");
        staticMap.put(177,"Brooklyn,Ocean Hill,Boro Zone");
        staticMap.put(178,"Brooklyn,Ocean Parkway South,Boro Zone");
        staticMap.put(179,"Queens,Old Astoria,Boro Zone");
        staticMap.put(180,"Queens,Ozone Park,Boro Zone");
        staticMap.put(181,"Brooklyn,Park Slope,Boro Zone");
        staticMap.put(182,"Bronx,Parkchester,Boro Zone");
        staticMap.put(183,"Bronx,Pelham Bay,Boro Zone");
        staticMap.put(184,"Bronx,Pelham Bay Park,Boro Zone");
        staticMap.put(185,"Bronx,Pelham Parkway,Boro Zone");
        staticMap.put(186,"Manhattan,Penn Station/Madison Sq West,Yellow Zone");
        staticMap.put(187,"Staten Island,Port Richmond,Boro Zone");
        staticMap.put(188,"Brooklyn,Prospect-Lefferts Gardens,Boro Zone");
        staticMap.put(189,"Brooklyn,Prospect Heights,Boro Zone");
        staticMap.put(190,"Brooklyn,Prospect Park,Boro Zone");
        staticMap.put(191,"Queens,Queens Village,Boro Zone");
        staticMap.put(192,"Queens,Queensboro Hill,Boro Zone");
        staticMap.put(193,"Queens,Queensbridge/Ravenswood,Boro Zone");
        staticMap.put(194,"Manhattan,Randalls Island,Yellow Zone");
        staticMap.put(195,"Brooklyn,Red Hook,Boro Zone");
        staticMap.put(196,"Queens,Rego Park,Boro Zone");
        staticMap.put(197,"Queens,Richmond Hill,Boro Zone");
        staticMap.put(198,"Queens,Ridgewood,Boro Zone");
        staticMap.put(199,"Bronx,Rikers Island,Boro Zone");
        staticMap.put(200,"Bronx,Riverdale/North Riverdale/Fieldston,Boro Zone");
        staticMap.put(201,"Queens,Rockaway Park,Boro Zone");
        staticMap.put(202,"Manhattan,Roosevelt Island,Boro Zone");
        staticMap.put(203,"Queens,Rosedale,Boro Zone");
        staticMap.put(204,"Staten Island,Rossville/Woodrow,Boro Zone");
        staticMap.put(205,"Queens,Saint Albans,Boro Zone");
        staticMap.put(206,"Staten Island,Saint George/New Brighton,Boro Zone");
        staticMap.put(207,"Queens,Saint Michaels Cemetery/Woodside,Boro Zone");
        staticMap.put(208,"Bronx,Schuylerville/Edgewater Park,Boro Zone");
        staticMap.put(209,"Manhattan,Seaport,Yellow Zone");
        staticMap.put(210,"Brooklyn,Sheepshead Bay,Boro Zone");
        staticMap.put(211,"Manhattan,SoHo,Yellow Zone");
        staticMap.put(212,"Bronx,Soundview/Bruckner,Boro Zone");
        staticMap.put(213,"Bronx,Soundview/Castle Hill,Boro Zone");
        staticMap.put(214,"Staten Island,South Beach/Dongan Hills,Boro Zone");
        staticMap.put(215,"Queens,South Jamaica,Boro Zone");
        staticMap.put(216,"Queens,South Ozone Park,Boro Zone");
        staticMap.put(217,"Brooklyn,South Williamsburg,Boro Zone");
        staticMap.put(218,"Queens,Springfield Gardens North,Boro Zone");
        staticMap.put(219,"Queens,Springfield Gardens South,Boro Zone");
        staticMap.put(220,"Bronx,Spuyten Duyvil/Kingsbridge,Boro Zone");
        staticMap.put(221,"Staten Island,Stapleton,Boro Zone");
        staticMap.put(222,"Brooklyn,Starrett City,Boro Zone");
        staticMap.put(223,"Queens,Steinway,Boro Zone");
        staticMap.put(224,"Manhattan,Stuy Town/Peter Cooper Village,Yellow Zone");
        staticMap.put(225,"Brooklyn,Stuyvesant Heights,Boro Zone");
        staticMap.put(226,"Queens,Sunnyside,Boro Zone");
        staticMap.put(227,"Brooklyn,Sunset Park East,Boro Zone");
        staticMap.put(228,"Brooklyn,Sunset Park West,Boro Zone");
        staticMap.put(229,"Manhattan,Sutton Place/Turtle Bay North,Yellow Zone");
        staticMap.put(230,"Manhattan,Times Sq/Theatre District,Yellow Zone");
        staticMap.put(231,"Manhattan,TriBeCa/Civic Center,Yellow Zone");
        staticMap.put(232,"Manhattan,Two Bridges/Seward Park,Yellow Zone");
        staticMap.put(233,"Manhattan,UN/Turtle Bay South,Yellow Zone");
        staticMap.put(234,"Manhattan,Union Sq,Yellow Zone");
        staticMap.put(235,"Bronx,University Heights/Morris Heights,Boro Zone");
        staticMap.put(236,"Manhattan,Upper East Side North,Yellow Zone");
        staticMap.put(237,"Manhattan,Upper East Side South,Yellow Zone");
        staticMap.put(238,"Manhattan,Upper West Side North,Yellow Zone");
        staticMap.put(239,"Manhattan,Upper West Side South,Yellow Zone");
        staticMap.put(240,"Bronx,Van Cortlandt Park,Boro Zone");
        staticMap.put(241,"Bronx,Van Cortlandt Village,Boro Zone");
        staticMap.put(242,"Bronx,Van Nest/Morris Park,Boro Zone");
        staticMap.put(243,"Manhattan,Washington Heights North,Boro Zone");
        staticMap.put(244,"Manhattan,Washington Heights South,Boro Zone");
        staticMap.put(245,"Staten Island,West Brighton,Boro Zone");
        staticMap.put(246,"Manhattan,West Chelsea/Hudson Yards,Yellow Zone");
        staticMap.put(247,"Bronx,West Concourse,Boro Zone");
        staticMap.put(248,"Bronx,West Farms/Bronx River,Boro Zone");
        staticMap.put(249,"Manhattan,West Village,Yellow Zone");
        staticMap.put(250,"Bronx,Westchester Village/Unionport,Boro Zone");
        staticMap.put(251,"Staten Island,Westerleigh,Boro Zone");
        staticMap.put(252,"Queens,Whitestone,Boro Zone");
        staticMap.put(253,"Queens,Willets Point,Boro Zone");
        staticMap.put(254,"Bronx,Williamsbridge/Olinville,Boro Zone");
        staticMap.put(255,"Brooklyn,Williamsburg (North Side),Boro Zone");
        staticMap.put(256,"Brooklyn,Williamsburg (South Side),Boro Zone");
        staticMap.put(257,"Brooklyn,Windsor Terrace,Boro Zone");
        staticMap.put(258,"Queens,Woodhaven,Boro Zone");
        staticMap.put(259,"Bronx,Woodlawn/Wakefield,Boro Zone");
        staticMap.put(260,"Queens,Woodside,Boro Zone");
        staticMap.put(261,"Manhattan,World Trade Center,Yellow Zone");
        staticMap.put(262,"Manhattan,Yorkville East,Yellow Zone");
        staticMap.put(263,"Manhattan,Yorkville West,Yellow Zone");
        staticMap.put(264,"Unknown,NV,N/A");
        staticMap.put(265,"Unknown,NA,N/A");
    }

}
