version: '2'

services:
  spark-master:
    image: docker.io/bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - 7077:7077
      - 4040:4040

  spark-worker:
    image: docker.io/bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker1:
    image: docker.io/bitnami/spark:latest
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  
  # flag -d da riga di comando ma pare che funziona lo stesso
  hdfs-master:
    image: matnar/hadoop:3.3.2
    container_name: hdfs-master
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 9870:9870
      - 54310:54310
    volumes:
      - ../target:/home
      - ../data:/home/data   

  datanode1:
    image: matnar/hadoop:3.3.2
    container_name: hdfs-worker1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 9864:9864

  datanode2:
    image: matnar/hadoop:3.3.2
    container_name: hdfs-worker2
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 9863:9864
      
  datanode3:
    image: matnar/hadoop:3.3.2
    container_name: hdfs-worker3
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 9862:9864

networks:
  default:
    name: proj1_network